### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by mahmoudkassem92** [codeontology/parser#1]
Hello,

I am getting this build error during executing the build command

Could not resolve dependencies for project org.codeontology:codeontology:jar:1.0-SNAPSHOT: Failure to find org.eclipse.jdt:org.eclipse.jdt.core:jar:3.12.0.v20150913-1717 in http://repo.spring.io/libs-milestone/ was cached in the local repository, resolution will not be reattempted until the update interval of spring-milestones has elapsed or updates are forced

**Comment by janfischerhhu** [comment]
Same problem over here.

**Comment by hualoveshao** [comment]
Try to check if the url of the dependent file version given in the file pom.xml exists.

**Comment by mattia-atzeni** [comment]
@mahmoudkassem92 thanks for opening this issue. I updated Eclipse JDT version to 3.12.3 in pom.xml, and now the project can be built successfully.
