### ISSUE TITLE
dependency file missing in http://repo.spring.io/libs-milestone/org/eclipse/jdt/org.eclipse.jdt.core/

### ISSUE THREAD

**Issue by Waqar-107** [codeontology/parser#2]
![thesis_build_error](https://user-images.githubusercontent.com/24852360/61509911-8c361a80-aa12-11e9-96fa-2dd49f559fc7.png)

looks like the dependency file is missing from where it is supposed to be downloaded so it is causing build failure. what should i do to resolve it?

**Comment by Waqar-107** [comment]
changed the version to 3.12.3 in the pom,xml (the highlighted part in the screenshot above) and the build succeeded.

**Comment by mattia-atzeni** [comment]
Thanks, I updated the pom.xml file.
