### ISSUE TITLE
codeontology Parser

### ISSUE THREAD

**Issue by Nodenot** [codeontology/parser#4]
After building it with mvn, I try to run the codeontology parser applied on a single java file, but i get the Following error :
C:\Users\nodenot\Downloads\parser-masterv2\parser-master>java -cp target/codeontology-1.0-SNAPSHOT-jar-with-dependencies.jar org.codeontology.CodeOntology -i ./../essai/ -o triples.nt
Running on ./../essai/
Dependencies loaded in 3 ms.
Building model...
It was a good plan that went awry.
The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files at C:\Users\nodenot\Downloads\parser-masterv2\essai\Application.java:1

Any idea ? Thks in advance

Rmk : to execute the parser with openjdk, I had to delete the following options : -d64 -Xms2G -Xmx4G from the .cmd file=> the command line is : 
java -cp target/codeontology-1.0-SNAPSHOT-jar-with-dependencies.jar org.codeontology.CodeOntology %CODEONTOLOGY_LINE_ARGS%'

**Comment by atzori** [comment]
Just pushed a commit that solves other issues, not this one actually.
It may depend on your code on Application.java.   @Nodenot Did you try to compile it? 
CodeOntology parser does not parse source code that have compiling issues.

@Nodenot

Just tried with the following:
```
// file Application.java
public class Application {

    public int mySum(int a , int b) {
        return a + b;
    }

}
```

and it works.
