### ISSUE TITLE
Build Error - may need to change pom.xml

### ISSUE THREAD

**Issue by Waqar-107** [codeontology/parser#5]
Got the following error though `3.12.0.v20150913-1717` is commented out.
![image](https://user-images.githubusercontent.com/24852360/92348861-2e710000-f0f6-11ea-9245-13991bebd290.png)

Removed the comment but still the same.
Also, I assume maven has changed their address, https://mvnrepository.com/artifact/org.eclipse/org.eclipse.jdt.core

**Comment by ncoop57** [comment]
Yeah, I ran into the same problem

**Comment by ncoop57** [comment]
@Waqar-107 So this issue is actually from the spoon 5.1.0 dependency. If you change that dependency to 5.5.0, that error is removed. However, when I did this, I get a new error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project codeontology: Compilation failure: Compilation failure: 
[ERROR] /scratch1/parser/src/main/java/org/codeontology/extraction/declaration/ExecutableEntity.java:[31,30] package spoon.reflect.internal does not exist
[ERROR] /scratch1/parser/src/main/java/org/codeontology/extraction/declaration/ExecutableEntity.java:[45,83] cannot find symbol
[ERROR]   symbol: class CtGenericElement
[ERROR] /scratch1/parser/src/main/java/org/codeontology/extraction/support/GenericDeclarationEntity.java:[24,33] cannot find symbol
[ERROR]   symbol:   class CtGenericElement
[ERROR]   location: package spoon.reflect.declaration
[ERROR] /scratch1/parser/src/main/java/org/codeontology/extraction/support/GenericDeclarationEntity.java:[28,53] cannot find symbol
[ERROR]   symbol: class CtGenericElement
[ERROR] /scratch1/parser/src/main/java/org/codeontology/extraction/declaration/ParameterizedTypeEntity.java:[28,30] package spoon.reflect.internal does not exist
[ERROR] /scratch1/parser/src/main/java/org/codeontology/extraction/declaration/TypeKind.java:[29,39] cannot find symbol
[ERROR]   symbol:   class SpoonClassNotFoundException
[ERROR]   location: package spoon.support.reflect.reference
[ERROR] -> [Help 1]
```

Any ideas?

**Comment by Waqar-107** [comment]
same here, don't know what's wrong. I once built it in my old device in a VM, no choice but to use that.

**Comment by atzori** [comment]
Thank you @Waqar-107 @ncoop57 for your help.
It seems that spoon 5.1.0 requires a version of org.eclipse.jdt.core that is not available on the specified mvnrepository.
Removing reference to mvnrepository.com seems to solve the problem. 
Newer versions of Spoon require more recent jdt dependencies, but they are not backward compatible, so they cannot be easily used on current codeontology parser codebase.
