### ISSUE TITLE
Release of raw Jar File

### ISSUE THREAD

**Issue by ncoop57** [codeontology/parser#6]
Hi, I have been trying to build the project, but have been unsuccessful due to changes in dependencies. Is it possible to have the jar file added to a release of the project so that it doesn't not have to be built?

**Comment by atzori** [comment]
Problem with building should be solved now. Anyway, we added a new release with the jar files (both normal jar and jar with dependencies). You can find it in releases here on github. Thank you @ncoop57 for the suggestion.
