### ISSUE TITLE
Query Loop Statement

### ISSUE THREAD

**Issue by Ehsasha** [codeontology/parser#7]
I want to find methods in source code that have a loop.
How is this possible by sparql query in codeontology?

**Comment by atzori** [comment]
Hi Ehsan,

"Loops" may occurs in different shapes, e.g. via recursion, `for` or `while` statements.
All can be found using CodeOntology.
For an example of SPARQL query for direct recursion, take a look at [the first example here](http://codeontology.org/examples).
Statements such as `for` and `while` should be found as strings within the `rdfs:label` of a `woc:BlockStatement` (see e.g. the [parsed graph in this example](http://codeontology.org/parser)).
