### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by filipnis** [codeontology/parser#9]
I'm having a problem building this project (on Windows) using Maven. It reports:
+ Could not resolve dependencies for project org.codeontology:codeontology:jar:1.0-SNAPSHOT: Failed to collect dependencies at fr.inria.gforge.spoon:spoon-core:jar:5.1.0 -> org.eclipse.jdt:org.eclipse.jdt.core:jar:3.12.0.v20150913-1717
+ Failed to collect dependencies at fr.inria.gforge.spoon:spoon-core:jar:5.1.0 -> org.eclipse.jdt:org.eclipse.jdt.core:jar:3.12.0.v20150913-1717
+ Failed to read artifact descriptor for org.eclipse.jdt:org.eclipse.jdt.core:jar:3.12.0.v20150913-1717
+ Could not transfer artifact org.eclipse.jdt:org.eclipse.jdt.core:pom:3.12.0.v20150913-1717 from/to spring-milestones (https://repo.spring.io/libs-milestone/): authentication failed for https://repo.spring.io/libs-milestone/org/eclipse/jdt/org.eclipse.jdt.core/3.12.0.v20150913-1717/org.eclipse.jdt.core-3.12.0.v20150913-1717.pom, status: 401 Unauthorized
+  Could not transfer artifact org.eclipse.jdt:org.eclipse.jdt.core:pom:3.12.0.v20150913-1717 from/to spring-milestones (https://repo.spring.io/libs-milestone/): authentication failed for https://repo.spring.io/libs-milestone/org/eclipse/jdt/org.eclipse.jdt.core/3.12.0.v20150913-1717/org.eclipse.jdt.core-3.12.0.v20150913-1717.pom, status: 401 Unauthorized
+  authentication failed for https://repo.spring.io/libs-milestone/org/eclipse/jdt/org.eclipse.jdt.core/3.12.0.v20150913-1717/org.eclipse.jdt.core-3.12.0.v20150913-1717.pom, status: 401 Unauthorized

Any idea what is wrong ?

**Comment by atzori** [comment]
Thank you for reporting the problem. With our last commit 94682f831c the issue should be solved.
